server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
jwt:
  secret: 65a4de4bd62a7c1e9c4373336b0fb8dc
  expiration: 180000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: "@project.name@"
    version: "@project.version@"